[Service]
Environment=FUTSI_CAMERA_BACKEND=v4l2-relay
Environment=FUTSI_MJPEG_RELAY_BIN=/usr/local/bin/faceguard-mjpeg-relay
Environment=FUTSI_MJPEG_RELAY_MAX_FPS=15
ExecStart=
ExecStart=/usr/local/bin/futsi-camera-stream /dev/video0 8080 60 3840x2160
ExecStartPre=
ExecStartPre=/usr/bin/v4l2-ctl -d /dev/video0 --set-ctrl=power_line_frequency=2
ExecStartPre=/usr/bin/v4l2-ctl -d /dev/video0 --set-ctrl=focus_automatic_continuous=1
