[Service]
Environment=FUTSI_CAMERA_BACKEND=v4l2-ffmpeg
ExecStartPre=
ExecStartPre=/usr/bin/v4l2-ctl -d /dev/video0 --set-ctrl=power_line_frequency=2
ExecStartPre=/usr/bin/v4l2-ctl -d /dev/video0 --set-ctrl=focus_automatic_continuous=1
