TERMS_VERSION = "registration-2026-10-08-v2"
TERMS = [
    "El que suscribe, por mi propio derecho, expresamente manifiesto que es mi deseo participar en los torneos de fútbol de Super Gol y B Power, aceptando todos los términos y condiciones estipulados en el escrito.",
    "Para poder participar en la liga de fútbol deberé cubrir con los puntos publicados en la convocatoria del torneo.",
    "Conozco la naturaleza de los torneos, así como las capacidades físicas y experiencia con la que cuento, manifestando que las mismas son idóneas para participar en los juegos de fútbol, en razón de lo anterior manifiesto encontrarme en perfecto estado de salud, tanto físico como mental para participar y desarrollar las actividades que se realicen dentro del mismo.",
    "Reconozco y acepto expresamente que las actividades que se realizan durante el evento son bajo mi propio riesgo, y que estoy consciente de que puede haber diversos riesgos que pueden resultar en esguinces, fracturas, descalabros y hasta la muerte; asumo dichos riesgos por completo.",
    "Libero de responsabilidad a cualquier persona o empleado que colabora con la Organización por cualquier lesión que sufra en la práctica de este deporte.",
    "Los objetos utilizados durante mi participación tales como lentes, guantes, calzado deportivo y cualquier otro usado por mi persona son mi responsabilidad dentro de las instalaciones, en caso de robo, pérdida o extravío de los mismos, los organizadores no serán responsables de cualquier situación antes mencionada.",
    "Los organizadores o cualquier persona física o moral relacionada de cualquier forma con la Organización o con el inmueble no serán responsables de cualquier daño, robo parcial o total de vehículos que ingresen a las instalaciones al ser mi total y plena responsabilidad.",
    "Acepto que los pagos realizados no serán reembolsables por ningún motivo, tampoco transferibles a cualquier tercero, retirarme del Torneo en cualquiera de sus etapas o si soy dado de baja por comisión disciplinaria por cualquier motivo estipulado dentro del reglamento o los estatutos internos de la liga.",
    "Como participante debo realizar el registro correspondiente ante los organizadores, sin dicho registro no podré participar en los Torneos y de ser necesario podrán retirarme de las instalaciones liberándolos de toda responsabilidad, en el caso de que el participante sea menor de edad, el Padre o Tutor acepta y reconoce los términos establecidos en el presente documento autorizando al menor a participar en el Torneo, asumiendo la responsabilidad de seguridad y bienestar. El padre o tutor del menor, en caso que no se firme dicha responsiva, el menor de edad no podrá participar en dicha actividad.",
    "Como participante me comprometí en revisar el Reglamento de Juego para conocer su contenido e informar de todas las reglas, estatutos y sanciones de la organización.",
    "Los empleados de la liga, el club y el colegio no se hacen responsables por ningún daño causado a los vehículos que ingresan.",
]
