# Generated by Django 5.2.14 on 2026-05-26 05:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courts',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rounds',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('close_editing_after_hours', models.PositiveSmallIntegerField(default=24)),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('representative_name', models.CharField(max_length=160)),
                ('representative_phone', models.CharField(max_length=30)),
                ('representative_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('accounting', 'Contador'), ('owner', 'Direccion'), ('site_coordinator', 'Coordinador de sede'), ('coach', 'Coach')], default='site_coordinator', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('primary_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='core.site')),
            ],
            options={
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('academy_class', 'Clase academia'), ('tournament_match', 'Partido torneo')], max_length=30)),
                ('date', models.DateField()),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=80)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_sessions', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='core.court')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.round')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='core.site')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team')),
            ],
            options={
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_name', models.CharField(blank=True, max_length=180)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'guardians',
                'indexes': [models.Index(fields=['full_name'], name='ix_guardian_full_name'), models.Index(fields=['phone'], name='ix_guardian_phone')],
            },
        ),
        migrations.AddField(
            model_name='court',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='core.site'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('group_name', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activo'), ('paused', 'Pausa'), ('injured', 'Lesion'), ('dropped', 'Baja')], default='trial', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/')),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=160)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('uniform_status', models.CharField(default='pending', max_length=40)),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.guardian')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.site')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_charges', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.site')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.team')),
            ],
            options={
                'db_table': 'charges',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='players/photos/')),
                ('identity_document', models.FileField(blank=True, upload_to='players/ids/')),
                ('waiver_document', models.FileField(blank=True, upload_to='players/waivers/')),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='core.team')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('courtesy', 'Cortesia')], max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('reconciled', 'Conciliado'), ('canceled', 'Cancelado')], default='registered', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('tracking_key', models.CharField(blank=True, max_length=120)),
                ('receipt_file', models.FileField(blank=True, upload_to='payments/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.charge')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.site')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.team')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('canceled', 'Cancelado')], default='requested', max_length=20)),
                ('evidence_file', models.FileField(blank=True, upload_to='discounts/evidence/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='core.charge')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_discounts', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='core.site')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='core.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='core.team')),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Asistio'), ('absent', 'Falto'), ('justified', 'Justificada')], max_length=20)),
                ('had_debt_at_capture', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.team')),
            ],
            options={
                'db_table': 'attendance_records',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('billing_type', models.CharField(choices=[('full_tournament', 'Torneo completo'), ('weekly_match', 'Pago semanal')], max_length=30)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('expected_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='core.site')),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='core.tournament'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='core.tournament'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tournament'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('table_name', models.CharField(max_length=80)),
                ('record_id', models.CharField(max_length=80)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='ix_audit_table_record'), models.Index(fields=['actor', 'created_at'], name='ix_audit_actor_created')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('provider_name', models.CharField(blank=True, max_length=160)),
                ('evidence_file', models.FileField(blank=True, upload_to='expenses/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_expenses', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.site')),
            ],
            options={
                'db_table': 'expenses',
                'indexes': [models.Index(fields=['site', 'expense_date'], name='ix_expense_site_date'), models.Index(fields=['site', 'status'], name='ix_expense_site_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_expense_amount')],
            },
        ),
        migrations.CreateModel(
            name='DailyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_reported', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_reopened', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closures', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closures', to='core.site')),
            ],
            options={
                'db_table': 'daily_closures',
                'constraints': [models.UniqueConstraint(fields=('site', 'business_date'), name='uq_daily_closure_site_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uq_court_site_name'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['site', 'status'], name='ix_student_site_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='ix_student_full_name'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'is_active'], name='ix_player_team_active'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['site', 'paid_at'], name='ix_payment_site_paid_at'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='ix_payment_method_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tracking_key'], name='ix_payment_tracking_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_payment_amount'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['site', 'status'], name='ix_discount_site_status'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['student', 'status'], name='ix_discount_student_status'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['team', 'status'], name='ix_discount_team_status'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_discount_amount'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['site', 'status'], name='ix_charge_site_status'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['student', 'status'], name='ix_charge_student_status'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['team', 'status'], name='ix_charge_team_status'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_charge_amount'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('team__isnull', True)), models.Q(('student__isnull', True), ('team__isnull', False)), _connector='OR'), name='ck_charge_subject'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='ix_att_record_session_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='ix_att_record_student'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['team'], name='ix_att_record_team'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('team__isnull', True)), models.Q(('student__isnull', True), ('team__isnull', False)), _connector='OR'), name='ck_attendance_record_subject'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['site', 'is_active'], name='ix_tournament_site_active'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uq_team_tournament_name'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='uq_round_tournament_number'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['site', 'date'], name='ix_att_session_site_date'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_type', 'date'], name='ix_att_session_type_date'),
        ),
    ]
