# Generated by Django 5.2.14 on 2026-05-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('accounting', 'Contador'), ('owner', 'Direccion'), ('site_coordinator', 'Coordinador de sede'), ('coach', 'Coach'), ('guardian', 'Representante')], default='site_coordinator', max_length=32),
        ),
    ]
