# Generated by Django 5.2.14 on 2026-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guardian_user_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('accounting', 'Contador'), ('owner', 'Direccion'), ('site_coordinator', 'Coordinador de sede'), ('cashier', 'Cajero'), ('coach', 'Coach'), ('guardian', 'Representante')], default='site_coordinator', max_length=32),
        ),
    ]
