# Generated by Django 5.2.14 on 2026-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='virtual_clabe',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, choices=[('cash_confirmation', 'Efectivo con aceptacion'), ('transfer_clabe', 'Transferencia CLABE'), ('card_terminal', 'Terminal'), ('card_link', 'Link de pago'), ('courtesy', 'Cortesia')], max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('processing', 'En proceso'), ('awaiting_confirmation', 'Pendiente de aceptacion'), ('registered', 'Registrado'), ('reconciled', 'Conciliado'), ('canceled', 'Cancelado'), ('expired', 'Expirado')], default='registered', max_length=32),
        ),
    ]
