# Generated by Django 5.2.14 on 2026-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pause_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='student',
            name='pause_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='waiver_url',
            field=models.URLField(blank=True),
        ),
    ]
