# Generated by Django 5.2.14 on 2026-05-26 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_pause_end_student_pause_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_group_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='coach_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CoachWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(blank=True, max_length=80)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.CharField(default='Entrenamiento', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_work_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_coach_work_logs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_work_logs', to='core.site')),
            ],
            options={
                'db_table': 'coach_work_logs',
                'indexes': [models.Index(fields=['coach', 'work_date'], name='ix_coach_log_coach_date'), models.Index(fields=['site', 'work_date'], name='ix_coach_log_site_date')],
            },
        ),
    ]
