# Generated by Django 5.2.14 on 2026-05-27 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_coach_group_name_user_coach_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('engine', models.CharField(default='mock', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='face_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attempts', to='core.attendancesession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_attempts', to='core.student')),
            ],
            options={
                'db_table': 'face_recognition_attempts',
                'indexes': [models.Index(fields=['session', 'matched'], name='ix_face_attempt_session_match'), models.Index(fields=['student', 'created_at'], name='ix_face_attempt_student_date')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Emitida'), ('canceled', 'Cancelada')], default='issued', max_length=20)),
                ('recipient_name', models.CharField(max_length=180)),
                ('recipient_tax_id', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('concept', models.CharField(max_length=180)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('xml_content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/pdf/')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.charge')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coach_invoices', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.expense')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.guardian')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.payment')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.site')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.student')),
            ],
            options={
                'db_table': 'invoices',
                'indexes': [models.Index(fields=['kind', 'status'], name='ix_invoice_kind_status'), models.Index(fields=['student', 'issued_at'], name='ix_invoice_student_date'), models.Index(fields=['guardian', 'issued_at'], name='ix_invoice_guardian_date'), models.Index(fields=['expense', 'issued_at'], name='ix_invoice_expense_date')],
            },
        ),
    ]
