# Generated by Django 5.2.14 on 2026-05-28 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facerecognitionattempt_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(upload_to='historical/imports/')),
                ('original_filename', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Preview'), ('committed', 'Confirmado'), ('canceled', 'Cancelado')], default='draft', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_name', models.CharField(blank=True, max_length=180)),
                ('signature_role', models.CharField(blank=True, max_length=80)),
                ('source_password_used', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='committed_historical_imports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historical_imports',
            },
        ),
        migrations.CreateModel(
            name='HistoricalImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_type', models.CharField(max_length=20)),
                ('sheet_name', models.CharField(max_length=80)),
                ('source_row', models.PositiveIntegerField()),
                ('month_label', models.CharField(blank=True, max_length=40)),
                ('site_name_raw', models.CharField(blank=True, max_length=140)),
                ('concept_code', models.CharField(blank=True, max_length=40)),
                ('concept', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('committed', 'Confirmado'), ('skipped', 'Omitido'), ('error', 'Error')], default='pending', max_length=20)),
                ('target_table', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('historical_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.historicalimport')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_rows', to='core.site')),
            ],
            options={
                'db_table': 'historical_import_rows',
            },
        ),
        migrations.AddIndex(
            model_name='historicalimport',
            index=models.Index(fields=['status', 'created_at'], name='ix_hist_import_status_date'),
        ),
        migrations.AddIndex(
            model_name='historicalimport',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='ix_hist_import_uploaded_by'),
        ),
        migrations.AddIndex(
            model_name='historicalimportrow',
            index=models.Index(fields=['historical_import', 'status'], name='ix_hist_row_import_status'),
        ),
        migrations.AddIndex(
            model_name='historicalimportrow',
            index=models.Index(fields=['row_type', 'record_date'], name='ix_hist_row_type_date'),
        ),
        migrations.AddIndex(
            model_name='historicalimportrow',
            index=models.Index(fields=['site', 'row_type'], name='ix_hist_row_site_type'),
        ),
    ]
