# Generated by Django 5.2.14 on 2026-06-01 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_dev_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played_on', models.DateField(default=django.utils.timezone.localdate)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('home_goals', models.PositiveSmallIntegerField(default=0)),
                ('away_goals', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En vivo'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='core.team')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='core.round')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='core.site')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='core.tournament')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'indexes': [models.Index(fields=['tournament', 'status'], name='ix_match_tournament_status'), models.Index(fields=['site', 'played_on'], name='ix_match_site_played_on')],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_month', models.DateField()),
                ('pace', models.PositiveSmallIntegerField(default=50)),
                ('shooting', models.PositiveSmallIntegerField(default=50)),
                ('passing', models.PositiveSmallIntegerField(default=50)),
                ('dribbling', models.PositiveSmallIntegerField(default=50)),
                ('defense', models.PositiveSmallIntegerField(default=50)),
                ('physical', models.PositiveSmallIntegerField(default=50)),
                ('attitude', models.PositiveSmallIntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='core.site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.student')),
            ],
            options={
                'db_table': 'student_assessments',
                'indexes': [models.Index(fields=['student', 'assessment_month'], name='ix_assessment_student_month'), models.Index(fields=['coach', 'assessment_month'], name='ix_assessment_coach_month')],
                'constraints': [models.UniqueConstraint(fields=('student', 'assessment_month'), name='uq_student_assessment_month'), models.CheckConstraint(condition=models.Q(('pace__gte', 0), ('pace__lte', 100)), name='ck_assessment_pace_range'), models.CheckConstraint(condition=models.Q(('shooting__gte', 0), ('shooting__lte', 100)), name='ck_assessment_shooting_range'), models.CheckConstraint(condition=models.Q(('passing__gte', 0), ('passing__lte', 100)), name='ck_assessment_passing_range'), models.CheckConstraint(condition=models.Q(('dribbling__gte', 0), ('dribbling__lte', 100)), name='ck_assessment_dribbling_range'), models.CheckConstraint(condition=models.Q(('defense__gte', 0), ('defense__lte', 100)), name='ck_assessment_defense_range'), models.CheckConstraint(condition=models.Q(('physical__gte', 0), ('physical__lte', 100)), name='ck_assessment_physical_range'), models.CheckConstraint(condition=models.Q(('attitude__gte', 0), ('attitude__lte', 100)), name='ck_assessment_attitude_range')],
            },
        ),
    ]
