# Generated by Django 5.2.14 on 2026-06-02 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_match_studentassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('admin_payroll', 'Nomina administrativa'), ('coach_payroll', 'Nomina coaches'), ('referee_payroll', 'Nomina arbitros'), ('other_staff_payment', 'Otro pago a personal')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=220)),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('canceled', 'Cancelado')], default='requested', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payment_requests', to='core.expense')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_staff_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_payment_requests', to='core.site')),
            ],
            options={
                'db_table': 'staff_payment_requests',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('cash_in', 'Entrada de efectivo'), ('cash_out', 'Salida por gasto'), ('vault_transfer', 'Retiro a resguardo'), ('adjustment', 'Ajuste')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='core.site')),
                ('staff_payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='core.staffpaymentrequest')),
            ],
            options={
                'db_table': 'cash_movements',
            },
        ),
        migrations.AddIndex(
            model_name='staffpaymentrequest',
            index=models.Index(fields=['site', 'status'], name='ix_staff_payment_site_status'),
        ),
        migrations.AddIndex(
            model_name='staffpaymentrequest',
            index=models.Index(fields=['recipient', 'status'], name='ix_staff_pay_rec_status'),
        ),
        migrations.AddIndex(
            model_name='staffpaymentrequest',
            index=models.Index(fields=['requested_payment_date'], name='ix_staff_payment_date'),
        ),
        migrations.AddConstraint(
            model_name='staffpaymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_staff_payment_amount'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['site', 'movement_date'], name='ix_cash_movement_site_date'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['site', 'movement_type'], name='ix_cash_movement_site_type'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_cash_movement_amount'),
        ),
    ]
