# Generated by Django 5.2.14 on 2026-06-03 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_staffpaymentrequest_cashmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_player_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='representative_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_adult_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('dev', 'Dev App'), ('accounting', 'Contador'), ('owner', 'Direccion'), ('site_coordinator', 'Coordinador de sede'), ('cashier', 'Cajero'), ('coach', 'Coach'), ('guardian', 'Representante'), ('adult_representative', 'Representante adulto'), ('adult_player', 'Jugador adulto')], default='site_coordinator', max_length=32),
        ),
        migrations.CreateModel(
            name='PlayerAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Asistio'), ('absent', 'Falto'), ('justified', 'Justificada')], max_length=20)),
                ('had_team_debt_at_capture', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_player_attendance', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_records', to='core.attendancesession')),
            ],
            options={
                'db_table': 'player_attendance_records',
                'indexes': [models.Index(fields=['session', 'status'], name='ix_player_att_session_status'), models.Index(fields=['player'], name='ix_player_att_player')],
                'constraints': [models.UniqueConstraint(fields=('session', 'player'), name='uq_player_att_session_player')],
            },
        ),
    ]
