# Generated by Django 5.2.14 on 2026-06-11 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_player_email_player_jersey_number_player_photo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='registered', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_tournament_registrations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_registrations', to='core.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registrations', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_registrations', to='core.tournament')),
            ],
            options={
                'db_table': 'student_tournament_registrations',
                'indexes': [models.Index(fields=['tournament', 'status'], name='ix_stu_tourn_reg_tourn_status'), models.Index(fields=['student'], name='ix_stu_tourn_reg_student')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'student'), name='uq_student_tournament_registration')],
            },
        ),
    ]
