# Generated by Django 5.2.14 on 2026-06-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_studenttournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='jornada_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='tournament_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.studenttournamentregistration'),
        ),
        migrations.AddField(
            model_name='studenttournamentregistration',
            name='billing_starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttournamentregistration',
            name='billing_type',
            field=models.CharField(choices=[('full_tournament', 'Torneo completo'), ('weekly_match', 'Pago semanal')], default='weekly_match', max_length=30),
        ),
        migrations.AddField(
            model_name='studenttournamentregistration',
            name='full_amount',
            field=models.DecimalField(decimal_places=2, default=7800, max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttournamentregistration',
            name='weekly_amount',
            field=models.DecimalField(decimal_places=2, default=650, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['tournament_registration', 'status'], name='ix_charge_tourn_reg_status'),
        ),
        migrations.AddIndex(
            model_name='studenttournamentregistration',
            index=models.Index(fields=['billing_type', 'status'], name='ix_stu_reg_bill_status'),
        ),
    ]
