# Generated by Django 5.2.14 on 2026-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_charge_jornada_number_charge_tournament_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
