# Generated by Django 5.2.14 on 2026-06-16 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attendancesession_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentValueAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_month', models.DateField()),
                ('respect', models.PositiveSmallIntegerField(default=50)),
                ('discipline', models.PositiveSmallIntegerField(default=50)),
                ('teamwork', models.PositiveSmallIntegerField(default=50)),
                ('responsibility', models.PositiveSmallIntegerField(default=50)),
                ('sportsmanship', models.PositiveSmallIntegerField(default=50)),
                ('minutes_recommendation', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_value_assessments', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_value_assessments', to='core.site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_assessments', to='core.student')),
            ],
            options={
                'db_table': 'student_value_assessments',
                'indexes': [models.Index(fields=['student', 'assessment_month'], name='ix_value_student_month'), models.Index(fields=['coach', 'assessment_month'], name='ix_value_coach_month'), models.Index(fields=['site', 'assessment_month'], name='ix_value_site_month')],
                'constraints': [models.UniqueConstraint(fields=('student', 'assessment_month'), name='uq_student_value_month'), models.CheckConstraint(condition=models.Q(('respect__gte', 0), ('respect__lte', 100)), name='ck_value_respect_range'), models.CheckConstraint(condition=models.Q(('discipline__gte', 0), ('discipline__lte', 100)), name='ck_value_discipline_range'), models.CheckConstraint(condition=models.Q(('teamwork__gte', 0), ('teamwork__lte', 100)), name='ck_value_teamwork_range'), models.CheckConstraint(condition=models.Q(('responsibility__gte', 0), ('responsibility__lte', 100)), name='ck_value_responsibility_range'), models.CheckConstraint(condition=models.Q(('sportsmanship__gte', 0), ('sportsmanship__lte', 100)), name='ck_value_sportsmanship_range')],
            },
        ),
    ]
