# Generated by Django 5.2.15 on 2026-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_studentvalueassessment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('session', 'student'), name='uq_att_record_session_student'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('session', 'team'), name='uq_att_record_session_team'),
        ),
    ]
