# Generated by Django 5.2.14 on 2026-07-20 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_discount_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceStationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('camera_id', models.CharField(default='cancha_1', max_length=80)),
                ('secret_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='face_station_devices', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='face_station_devices', to='core.site')),
            ],
            options={
                'db_table': 'face_station_devices',
            },
        ),
        migrations.CreateModel(
            name='FaceStationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(unique=True)),
                ('person_type', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('detection_count', models.PositiveIntegerField(default=1)),
                ('similarity', models.FloatField(default=0)),
                ('source_subject_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('synced', 'Sincronizado'), ('no_session', 'Sin sesion'), ('rejected', 'Rechazado')], default='synced', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.facestationdevice')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='face_station_events', to='core.player')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_station_events', to='core.attendancesession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='face_station_events', to='core.student')),
            ],
            options={
                'db_table': 'face_station_events',
            },
        ),
        migrations.CreateModel(
            name='FaceStationUnknownLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_subject_id', models.CharField(max_length=80)),
                ('person_type', models.CharField(max_length=20)),
                ('remote_subject_id', models.UUIDField(blank=True, null=True)),
                ('evidence_uri', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_links', to='core.facestationdevice')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='face_station_unknown_links', to='core.player')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='face_station_unknown_links', to='core.student')),
            ],
            options={
                'db_table': 'face_station_unknown_links',
            },
        ),
        migrations.AddIndex(
            model_name='facestationdevice',
            index=models.Index(fields=['site', 'is_active'], name='ix_face_station_site_active'),
        ),
        migrations.AddIndex(
            model_name='facestationdevice',
            index=models.Index(fields=['last_seen_at'], name='ix_face_station_last_seen'),
        ),
        migrations.AddIndex(
            model_name='facestationevent',
            index=models.Index(fields=['device', 'occurred_at'], name='ix_face_station_device_time'),
        ),
        migrations.AddIndex(
            model_name='facestationevent',
            index=models.Index(fields=['student', 'occurred_at'], name='ix_face_station_student_time'),
        ),
        migrations.AddIndex(
            model_name='facestationevent',
            index=models.Index(fields=['player', 'occurred_at'], name='ix_face_station_player_time'),
        ),
        migrations.AddConstraint(
            model_name='facestationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('person_type', 'student'), ('player__isnull', True), ('student__isnull', False)), models.Q(('person_type', 'player'), ('player__isnull', False), ('student__isnull', True)), _connector='OR'), name='ck_face_station_event_person'),
        ),
        migrations.AddConstraint(
            model_name='facestationunknownlink',
            constraint=models.UniqueConstraint(fields=('device', 'local_subject_id'), name='uq_face_station_unknown_local'),
        ),
        migrations.AddConstraint(
            model_name='facestationunknownlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('person_type', 'student'), ('player__isnull', True), ('student__isnull', False)), models.Q(('person_type', 'player'), ('player__isnull', False), ('student__isnull', True)), _connector='OR'), name='ck_face_station_unknown_person'),
        ),
    ]
