# Generated by Django 5.2.16 on 2026-07-24 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_face_station_devices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facestationevent',
            name='ck_face_station_event_person',
        ),
        migrations.RemoveConstraint(
            model_name='facestationunknownlink',
            name='ck_face_station_unknown_person',
        ),
        migrations.AddField(
            model_name='facestationevent',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='face_station_attendance_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facestationunknownlink',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='face_station_unknown_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('dev', 'Dev App'), ('accounting', 'Contador'), ('owner', 'Direccion'), ('site_coordinator', 'Coordinador de sede'), ('cashier', 'Cajero'), ('coach', 'Coach'), ('collaborator', 'Colaborador'), ('guardian', 'Representante'), ('adult_representative', 'Representante adulto'), ('adult_player', 'Jugador adulto')], default='site_coordinator', max_length=32),
        ),
        migrations.AddIndex(
            model_name='facestationevent',
            index=models.Index(fields=['collaborator', 'occurred_at'], name='ix_face_station_collab_time'),
        ),
        migrations.AddConstraint(
            model_name='facestationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collaborator__isnull', True), ('person_type', 'student'), ('player__isnull', True), ('student__isnull', False)), models.Q(('collaborator__isnull', True), ('person_type', 'player'), ('player__isnull', False), ('student__isnull', True)), models.Q(('collaborator__isnull', False), ('person_type', 'collaborator'), ('player__isnull', True), ('student__isnull', True)), _connector='OR'), name='ck_face_station_event_person'),
        ),
        migrations.AddConstraint(
            model_name='facestationunknownlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collaborator__isnull', True), ('person_type', 'student'), ('player__isnull', True), ('student__isnull', False)), models.Q(('collaborator__isnull', True), ('person_type', 'player'), ('player__isnull', False), ('student__isnull', True)), models.Q(('collaborator__isnull', False), ('person_type', 'collaborator'), ('player__isnull', True), ('student__isnull', True)), _connector='OR'), name='ck_face_station_unknown_person'),
        ),
    ]
