# Generated by Django 5.2.14 on 2026-07-29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PROTECTED_TABLES = (
    "trial_bookings",
    "trial_visits",
    "voice_calls",
    "call_transcript_segments",
    "trial_availability_rules",
)


def protect_trial_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in PROTECTED_TABLES:
        schema_editor.execute(
            f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY'
        )
        for role in ("anon", "authenticated"):
            schema_editor.execute(
                f"""
                DO $do$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_roles WHERE rolname = '{role}'
                    ) THEN
                        EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE public."{table}" FROM {role}';
                    END IF;
                END
                $do$;
                """
            )


def unprotect_trial_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    # The tables are dropped immediately after this reverse operation. Do not
    # grant privileges that may not have existed before the migration.
    for table in PROTECTED_TABLES:
        schema_editor.execute(
            f"""
            DO $do$
            BEGIN
                IF to_regclass('public."{table}"') IS NOT NULL THEN
                    EXECUTE 'ALTER TABLE public."{table}" DISABLE ROW LEVEL SECURITY';
                END IF;
            END
            $do$;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_face_station_monthly_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responsible_name", models.CharField(max_length=160)),
                ("responsible_phone", models.CharField(max_length=30)),
                (
                    "responsible_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("child_first_name", models.CharField(max_length=100)),
                (
                    "child_age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(17),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("voice", "Llamada"),
                            ("manual", "Manual"),
                            ("web", "Web"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("in_progress", "En curso"),
                            ("completed", "Completada"),
                            ("canceled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trial_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_bookings",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "trial_bookings",
            },
        ),
        migrations.CreateModel(
            name="TrialVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("completed", "Completada"),
                            ("no_show", "No asistio"),
                            ("canceled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="core.trialbooking",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_visits",
                        to="core.court",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_visits",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "trial_visits",
                "ordering": ["starts_at", "visit_number"],
            },
        ),
        migrations.CreateModel(
            name="VoiceCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("call_sid", models.CharField(max_length=64, unique=True)),
                ("stream_sid", models.CharField(blank=True, max_length=80)),
                ("from_number", models.CharField(max_length=32)),
                ("to_number", models.CharField(max_length=32)),
                (
                    "technical_status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("ringing", "Sonando"),
                            ("in-progress", "En curso"),
                            ("completed", "Completada"),
                            ("busy", "Ocupado"),
                            ("failed", "Fallida"),
                            ("no-answer", "Sin respuesta"),
                            ("canceled", "Cancelada"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                (
                    "ai_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("successful", "Exitosa"),
                            ("unsuccessful", "No exitosa"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "review_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("successful", "Exitosa"),
                            ("unsuccessful", "No exitosa"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("sanitized_error", models.TextField(blank=True)),
                ("consent_granted", models.BooleanField(default=False)),
                (
                    "consent_granted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_calls",
                        to="core.trialbooking",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_voice_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_calls",
            },
        ),
        migrations.CreateModel(
            name="CallTranscriptSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "speaker",
                    models.CharField(
                        choices=[
                            ("caller", "Persona que llama"),
                            ("assistant", "Asistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("item_id", models.CharField(blank=True, max_length=128)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_segments",
                        to="core.voicecall",
                    ),
                ),
            ],
            options={
                "db_table": "call_transcript_segments",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="TrialAvailabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        help_text="0=lunes, 6=domingo",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "slot_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_availability_rules",
                        to="core.court",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_availability_rules",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "db_table": "trial_availability_rules",
                "ordering": ["site", "weekday", "starts_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "weekday", "is_active"],
                        name="ix_trial_avail_site_day_active",
                    ),
                    models.Index(
                        fields=["court", "weekday", "is_active"],
                        name="ix_trial_avail_court_active",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="ck_trial_availability_weekday",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="ck_trial_availability_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("slot_minutes__gte", 1)),
                        name="ck_trial_availability_slot_minutes",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gte", 1)),
                        name="ck_trial_availability_capacity",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(
                fields=["site", "status"],
                name="ix_trial_booking_site_status",
            ),
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(
                fields=["source", "created_at"],
                name="ix_trial_booking_source_date",
            ),
        ),
        migrations.AddIndex(
            model_name="trialbooking",
            index=models.Index(
                fields=["responsible_phone"],
                name="ix_trial_booking_phone",
            ),
        ),
        migrations.AddIndex(
            model_name="trialvisit",
            index=models.Index(
                fields=["site", "starts_at"],
                name="ix_trial_visit_site_start",
            ),
        ),
        migrations.AddIndex(
            model_name="trialvisit",
            index=models.Index(
                fields=["site", "status"],
                name="ix_trial_visit_site_status",
            ),
        ),
        migrations.AddIndex(
            model_name="trialvisit",
            index=models.Index(
                fields=["court", "starts_at"],
                name="ix_trial_visit_court_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialvisit",
            constraint=models.UniqueConstraint(
                fields=("booking", "visit_number"),
                name="uq_trial_visit_booking_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialvisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("visit_number__gte", 1), ("visit_number__lte", 2)),
                name="ck_trial_visit_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialvisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="ck_trial_visit_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="voicecall",
            index=models.Index(
                fields=["technical_status", "created_at"],
                name="ix_voice_call_status_date",
            ),
        ),
        migrations.AddIndex(
            model_name="voicecall",
            index=models.Index(
                fields=["review_outcome", "created_at"],
                name="ix_voice_call_review_date",
            ),
        ),
        migrations.AddIndex(
            model_name="voicecall",
            index=models.Index(
                fields=["booking", "created_at"],
                name="ix_voice_call_booking_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="voicecall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("review_outcome", "pending"),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                    ),
                    models.Q(
                        ("review_outcome__in", ["successful", "unsuccessful"]),
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_voice_call_review_audit",
            ),
        ),
        migrations.AddConstraint(
            model_name="calltranscriptsegment",
            constraint=models.UniqueConstraint(
                fields=("call", "sequence"),
                name="uq_call_transcript_sequence",
            ),
        ),
        migrations.RunPython(
            protect_trial_tables,
            reverse_code=unprotect_trial_tables,
        ),
    ]
