# Generated by Django 5.2.14 on 2026-08-04 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_voice_call_consent_withdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialbooking",
            name="source",
            field=models.CharField(
                choices=[
                    ("voice", "Llamada"),
                    ("whatsapp", "WhatsApp"),
                    ("manual", "Manual"),
                    ("web", "Web"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact_phone", models.CharField(max_length=32)),
                ("from_address", models.CharField(max_length=64)),
                ("to_address", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("completed", "Completada"),
                            ("canceled", "Cancelada"),
                            ("failed", "Fallida"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("choose_site", "Elegir sede"),
                            ("responsible_name", "Nombre del responsable"),
                            ("child_name", "Nombre del alumno"),
                            ("child_age", "Edad del alumno"),
                            ("choose_first_visit", "Elegir primera visita"),
                            ("choose_second_visit", "Elegir segunda visita"),
                            ("confirm", "Confirmar"),
                            ("finished", "Finalizada"),
                        ],
                        default="choose_site",
                        max_length=32,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_conversations",
                        to="core.trialbooking",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_conversations",
                        to="core.site",
                    ),
                ),
            ],
            options={"db_table": "whatsapp_conversations"},
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_sid",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "in_reply_to_sid",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Entrante"), ("outbound", "Saliente")],
                        max_length=12,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.whatsappconversation",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["status", "last_message_at"], name="ix_wa_status_message"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(fields=["site", "created_at"], name="ix_wa_site_created"),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["booking", "created_at"], name="ix_wa_booking_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("contact_phone",),
                name="uq_whatsapp_active_contact",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["conversation", "created_at"], name="ix_wa_msg_conversation"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["direction", "created_at"], name="ix_wa_msg_direction"
            ),
        ),
    ]
