# Generated by Django 5.2.14 on 2026-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("core", "0038_alter_whatsappconversation_current_step")]

    dependencies = [
        ('core', '0040_whatsapp_message_meta_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconversation',
            name='current_step',
            field=models.CharField(choices=[('menu', 'Menú principal'), ('faq', 'Preguntas y respuestas'), ('choose_site', 'Elegir sede'), ('responsible_name', 'Nombre del responsable'), ('child_name', 'Nombre del alumno'), ('child_age', 'Edad del alumno'), ('choose_first_visit', 'Elegir primera visita'), ('choose_second_visit', 'Elegir segunda visita'), ('confirm', 'Confirmar'), ('finished', 'Finalizada')], default='choose_site', max_length=32),
        ),
    ]
