# Generated by Django 5.2.14 on 2026-09-03 21:37

import core.models
import datetime
import django.core.validators
from django.db import migrations, models


def enable_row_level_security(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE whatsapp_automation_settings ENABLE ROW LEVEL SECURITY"
        )


def disable_row_level_security(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE whatsapp_automation_settings DISABLE ROW LEVEL SECURITY"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_scope_whatsapp_conversations_by_business_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_address', models.CharField(max_length=64, unique=True)),
                ('human_first_enabled', models.BooleanField(default=True)),
                ('business_days', models.JSONField(default=core.models.default_whatsapp_business_days)),
                ('business_hours_start', models.TimeField(default=datetime.time(9, 0))),
                ('business_hours_end', models.TimeField(default=datetime.time(18, 0))),
                ('human_response_delay_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
            ],
            options={
                'verbose_name': 'configuración de automatización de WhatsApp',
                'verbose_name_plural': 'configuraciones de automatización de WhatsApp',
                'db_table': 'whatsapp_automation_settings',
            },
        ),
        migrations.RunPython(
            enable_row_level_security,
            reverse_code=disable_row_level_security,
        ),
    ]
