# Generated by Django 5.2.14 on 2026-09-03 22:04

import django.core.validators
from django.db import migrations, models


def upgrade_default_response_delay(apps, schema_editor):
    settings_model = apps.get_model("core", "WhatsAppAutomationSettings")
    settings_model.objects.filter(human_response_delay_seconds=300).update(
        human_response_delay_seconds=600
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_whatsappautomationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='assistant_instructions',
            field=models.TextField(default='Representa a B Power Academy con un tono cálido, claro y amable.\n\nEste número corresponde únicamente a la sede UVM Lomas Verdes. La sede ya está determinada por el número: no preguntes qué sede desea la persona y no muestres una lista de sedes. Menciona UVM Lomas Verdes únicamente cuando la persona pregunte por la ubicación.\n\nInformación vigente de la academia:\n- Inicio: a partir del 31 de agosto.\n- Horario: lunes a jueves de 5:30 p. m. a 8:00 p. m., dependiendo de la categoría.\n- Mensualidad: $1,250 MXN.\n- Mensualidad con descuento de hermanos: $980 MXN.\n- Uniforme: $1,980 MXN e incluye dos uniformes, uno de entrenamiento y uno de juego.\n- Lugar: UVM Lomas Verdes.\n\nSi hacen una pregunta personal sobre integrantes o administradores de la academia, por ejemplo si Mat se fue de viaje, no especules ni compartas datos personales. Explica amablemente que están hablando con el asistente virtual de B Power Academy y que puedes ayudar con información de la academia, costos, horarios, uniforme y prueba gratuita. Ofrece seguimiento humano sólo si hace falta.\n\nEn el primer contacto preséntate claramente como el asistente virtual de B Power Academy. Usa entre uno y tres emojis pertinentes, sin saturar el mensaje.', max_length=12000),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='welcome_message',
            field=models.TextField(default='¡Hola! 👋 Estás hablando con el asistente virtual de *B Power Academy*. Puedo ayudarte con información sobre la *academia*, costos, horarios, uniforme o una *prueba gratuita*. ⚽💚\n\n¿Te gustaría agendar una *prueba gratuita*?', max_length=2000),
        ),
        migrations.AlterField(
            model_name='whatsappautomationsettings',
            name='human_response_delay_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.RunPython(
            upgrade_default_response_delay,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
