# Generated by Django 5.2.14 on 2026-09-04 00:01

import django.db.models.deletion
from django.db import migrations, models


def enable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE "whatsapp_outbound_dispatches" ENABLE ROW LEVEL SECURITY;'
        )


def disable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE "whatsapp_outbound_dispatches" DISABLE ROW LEVEL SECURITY;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_whatsapp_assistant_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOutboundDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_reply_to_sid', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reservado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('uncertain', 'Entrega no confirmada')], default='reserved', max_length=16)),
                ('delivery_kind', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('body', models.TextField()),
                ('provider_sid', models.CharField(blank=True, max_length=255)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_dispatches', to='core.whatsappconversation')),
            ],
            options={
                'db_table': 'whatsapp_outbound_dispatches',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ix_wa_dispatch_status')],
            },
        ),
        migrations.RunPython(
            enable_row_level_security,
            reverse_code=disable_row_level_security,
        ),
    ]
