# Generated by Django 5.2.14 on 2026-09-04 00:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enable_row_level_security(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE "whatsapp_human_response_events" ENABLE ROW LEVEL SECURITY;'
        )


def disable_row_level_security(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE "whatsapp_human_response_events" DISABLE ROW LEVEL SECURITY;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_whatsapp_outbound_dispatch_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='classification_confidence_threshold',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='contact_classification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='out_of_hours_acknowledgement',
            field=models.TextField(default='¡Gracias por escribirnos! 😊 Recibimos tu mensaje. En este momento estamos fuera de horario; una persona del equipo de B Power Academy te responderá en el próximo horario de atención. ⚽💚', max_length=2000),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='classification_confidence',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='classification_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='contact_type',
            field=models.CharField(choices=[('unclassified', 'Sin clasificar'), ('prospect', 'Prospecto nuevo'), ('current_client', 'Cliente actual'), ('ambiguous', 'Caso ambiguo')], default='unclassified', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='known_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='response_source',
            field=models.CharField(choices=[('unknown', 'Sin identificar'), ('bot', 'Asistente virtual'), ('human_dashboard', 'Persona desde FUTSI'), ('human_whatsapp', 'Persona desde WhatsApp Business')], default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='routing_decision',
            field=models.CharField(choices=[('unclassified', 'Sin clasificar'), ('bot_immediate', 'Respuesta inmediata del bot'), ('human_only', 'Atención humana'), ('bot_delayed', 'Bot después de espera'), ('out_of_hours_ack', 'Acuse fuera de horario'), ('automation_paused', 'Control humano activo')], default='unclassified', max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='within_business_hours',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppHumanResponseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('unclassified', 'Sin clasificar'), ('prospect', 'Prospecto nuevo'), ('current_client', 'Cliente actual'), ('ambiguous', 'Caso ambiguo')], default='unclassified', max_length=20)),
                ('human_attention_expected', models.BooleanField(default=True)),
                ('within_business_hours', models.BooleanField(default=True)),
                ('first_inbound_at', models.DateTimeField()),
                ('response_channel', models.CharField(choices=[('none', 'Sin respuesta humana'), ('dashboard', 'FUTSI'), ('whatsapp_business', 'WhatsApp Business')], default='none', max_length=24)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_response_events', to='core.whatsappconversation')),
                ('first_inbound_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_response_event', to='core.whatsappmessage')),
                ('responder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_human_responses', to=settings.AUTH_USER_MODEL)),
                ('response_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_human_response_event', to='core.whatsappmessage')),
            ],
            options={
                'db_table': 'whatsapp_human_response_events',
                'ordering': ['-first_inbound_at', '-id'],
                'indexes': [models.Index(fields=['first_inbound_at'], name='ix_wa_human_first_at'), models.Index(fields=['within_business_hours', 'first_inbound_at'], name='ix_wa_human_period'), models.Index(fields=['responded_at'], name='ix_wa_human_responded')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('responded_at__isnull', True)), fields=('conversation',), name='uq_wa_open_human_response')],
            },
        ),
        migrations.RunPython(
            enable_row_level_security,
            reverse_code=disable_row_level_security,
        ),
    ]
