# Generated by Django 5.2.14 on 2026-09-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_update_whatsapp_out_of_hours_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='openai_model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_settings', to='core.site'),
        ),
    ]
