# Generated by Django 5.2.14 on 2026-09-09 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def secure_plan_table(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute('ALTER TABLE billing_plans ENABLE ROW LEVEL SECURITY')
        # Django serves this data through authenticated, site-scoped endpoints.
        # Do not expose it through Supabase's public Data API.
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
            for (role,) in cursor.fetchall():
                schema_editor.execute(f'REVOKE ALL ON billing_plans FROM "{role}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_channel_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_key', models.UUIDField(unique=True)),
                ('concept', models.CharField(max_length=80)),
                ('first_due_date', models.DateField()),
                ('day_of_month', models.PositiveSmallIntegerField()),
                ('interval_months', models.PositiveSmallIntegerField(default=1)),
                ('installments', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_plans', to='core.student')),
                ('tournament_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_plans', to='core.studenttournamentregistration')),
            ],
            options={
                'db_table': 'billing_plans',
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='billing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.billingplan'),
        ),
        migrations.RunPython(secure_plan_table, migrations.RunPython.noop),
    ]
