# Generated by Django 5.2.14 on 2026-09-17 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_billing_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='charge',
            name='ck_charge_subject',
        ),
        migrations.AddField(
            model_name='charge',
            name='original_site_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='charge',
            name='original_student_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='charge',
            name='retained_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retained_charges', to='core.guardian'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charge',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.site'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discount',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='core.site'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.site'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('team__isnull', True)), models.Q(('student__isnull', True), ('team__isnull', False)), models.Q(('retained_guardian__isnull', False), ('student__isnull', True), ('team__isnull', True)), _connector='OR'), name='ck_charge_subject'),
        ),
    ]
