# Generated by Django 5.2.14 on 2026-09-15 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models

def secure_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        roles = [r[0] for r in cursor.fetchall()]
    for table in ('whatsapp_bulk_campaigns', 'whatsapp_bulk_recipients', 'whatsapp_bulk_receipts'):
        schema_editor.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        for role in roles:
            schema_editor.execute(f'REVOKE ALL ON {table} FROM "{role}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_whatsapp_bot_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBulkCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(db_index=True, max_length=64)),
                ('channel_kind', models.CharField(max_length=16)),
                ('actor_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('template', models.JSONField(default=dict)),
                ('quote', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('consent_at', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'whatsapp_bulk_campaigns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBulkReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=64)),
                ('message_id', models.CharField(max_length=255)),
                ('events', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'whatsapp_bulk_receipts',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('channel', 'message_id'), name='uq_bulk_receipt_channel_sid')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBulkRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.whatsappbulkcampaign')),
            ],
            options={
                'db_table': 'whatsapp_bulk_recipients',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('campaign', 'phone'), name='uq_bulk_campaign_phone')],
            },
        ),
        migrations.RunPython(secure_tables, migrations.RunPython.noop),
    ]
