# Generated by Django 5.2.18 on 2026-10-08 01:10

import core.enrollment_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_private_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        public_roles = [row[0] for row in cursor.fetchall()]
    for table in ("player_enrollment_invitations", "player_enrollments", "player_enrollment_documents"):
        schema_editor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        # Only the trusted Django database role should reach these tables.
        # No Data API policy is granted to public Supabase clients.
        for role in public_roles:
            schema_editor.execute(f'REVOKE ALL ON TABLE "{table}" FROM "{role}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_veronica_filter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEnrollmentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.enrollment_models.invitation_token, max_length=64, unique=True)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_enrollment_invitations',
            },
        ),
        migrations.CreateModel(
            name='PlayerEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('birth_date', models.DateField()),
                ('team', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('guardian_name', models.CharField(blank=True, max_length=160)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('document_checklist', models.JSONField(default=list)),
                ('terms_version', models.CharField(max_length=80)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.playerenrollmentinvitation')),
            ],
            options={
                'db_table': 'player_enrollments',
                'ordering': ['-signed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerEnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.playerenrollment')),
            ],
            options={
                'db_table': 'player_enrollment_documents',
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'kind'), name='uq_enrollment_document_kind')],
            },
        ),
        migrations.RunPython(protect_private_tables, migrations.RunPython.noop),
    ]
