# Generated by Django 5.2.18 on 2026-10-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_player_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerenrollment',
            name='identity_type',
            field=models.CharField(default='ine', max_length=20),
        ),
        migrations.AddField(
            model_name='playerenrollment',
            name='terms_text',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='playerenrollment',
            name='tournament',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='playerenrollmentinvitation',
            name='tournament',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
