# Generated by Django 5.2.18 on 2026-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_player_independent_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerenrollmentdocument',
            name='storage_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='playerenrollmentdocument',
            name='content',
            field=models.BinaryField(default=bytes),
        ),
    ]
