from django.db import migrations


def create_private_audit_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE TABLE IF NOT EXISTS whatsapp_quality_audits (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            channel varchar(64) NOT NULL,
            conversation_id bigint NOT NULL,
            period_end timestamptz NOT NULL,
            rubric varchar(32) NOT NULL,
            provider varchar(16) NOT NULL,
            model varchar(120) NOT NULL DEFAULT '',
            status varchar(16) NOT NULL DEFAULT 'pending',
            attempts smallint NOT NULL DEFAULT 0 CHECK (attempts >= 0),
            claim_id uuid NOT NULL,
            lease_until timestamptz,
            result jsonb NOT NULL DEFAULT '{}',
            usage jsonb NOT NULL DEFAULT '{}',
            detail varchar(120) NOT NULL DEFAULT '',
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_wa_quality_period UNIQUE (conversation_id, period_end, rubric)
        );
        CREATE INDEX IF NOT EXISTS wa_quality_channel_idx ON whatsapp_quality_audits(channel);
        CREATE INDEX IF NOT EXISTS wa_quality_period_idx ON whatsapp_quality_audits(period_end);
        ALTER TABLE whatsapp_quality_audits ENABLE ROW LEVEL SECURITY;
    """)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
        roles = [row[0] for row in cursor.fetchall()]
    for role in roles:
        schema_editor.execute(f'REVOKE ALL ON whatsapp_quality_audits FROM "{role}"')


class Migration(migrations.Migration):
    dependencies = [("core", "0061_enrollment_private_storage")]
    # Evaluation history is intentionally retained on rollback.
    operations = [migrations.RunPython(create_private_audit_table, migrations.RunPython.noop)]
