import { useEffect, useState } from "react";
import { Pencil, Plus, UserMinus, RotateCcw } from "lucide-react";
import type { StudentTournamentRegistration, Team } from "../../types";
import { SelectInput, TextInput } from "../../components/views/shared";
import { money } from "../../utils/format";

export function TournamentRoster({ registrations, teams, canEdit, onAdd, onEdit, onWithdraw, initialTeam = "" }: {
  registrations: StudentTournamentRegistration[]; teams: Team[]; canEdit: boolean; initialTeam?: string;
  onAdd: () => void; onEdit: (row: StudentTournamentRegistration) => void; onWithdraw: (row: StudentTournamentRegistration) => void;
}) {
  const [query, setQuery] = useState("");
  const [team, setTeam] = useState(initialTeam);
  const [status, setStatus] = useState("registered");
  const [page, setPage] = useState(0);
  const filtered = registrations.filter(row => (!status || row.status === status) && (!team || (team === "none" ? !row.team : String(row.team) === team)) && `${row.student_name} ${row.student_group_name} ${row.team_name || ""}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length / 12));
  useEffect(() => setPage(0), [query, team, status]);
  useEffect(() => setPage(current => Math.min(current, pages - 1)), [pages]);
  return <section className="tournament-surface" data-testid="tournament-roster"><header className="tournament-section-heading"><div><h3>Alumnos del torneo</h3><p>{registrations.filter(row => row.status === "registered").length} inscritos · {registrations.filter(row => row.status === "withdrawn").length} bajas</p></div>{canEdit && <button className="tournament-button primary" onClick={onAdd}><Plus size={16} />Inscribir alumno</button>}</header><div className="tournament-roster-filters"><TextInput label="Buscar alumno" placeholder="Nombre, grupo o equipo" value={query} onChange={event => setQuery(event.target.value)} /><SelectInput label="Equipo" value={team} onChange={event => setTeam(event.target.value)}><option value="">Todos los equipos</option><option value="none">Sin equipo asignado</option>{teams.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</SelectInput><SelectInput label="Inscripción" value={status} onChange={event => setStatus(event.target.value)}><option value="registered">Inscritos</option><option value="withdrawn">Bajas</option><option value="">Todos</option></SelectInput></div>
    <div className="tournament-table-scroll" role="region" aria-label="Alumnos del torneo, desplázate horizontalmente para ver todas las columnas" tabIndex={0}><table><thead><tr><th>Alumno</th><th>Equipo</th><th>Plan de pago</th><th>Estado</th>{canEdit && <th>Acciones</th>}</tr></thead><tbody>{filtered.slice(page * 12, (page + 1) * 12).map(row => <tr key={row.id}><th scope="row">{row.student_name}<small>{row.student_group_name || row.student_category || "Sin grupo"}{row.jersey_number ? ` · Camiseta ${row.jersey_number}` : ""}</small></th><td>{row.team_name || <span className="tournament-badge warning">Sin equipo</span>}</td><td>${money(row.billing_type === "full_tournament" ? row.full_amount : row.weekly_amount)}<small>{row.billing_type === "full_tournament" ? "Torneo completo" : "Por semana"}</small></td><td><span className={`tournament-badge ${row.status === "registered" ? "success" : "muted"}`}>{row.status === "registered" ? "Inscrito" : "Baja"}</span></td>{canEdit && <td><div className="tournament-row-actions"><button className="tournament-button secondary compact" aria-label={`${row.status === "registered" ? "Editar inscripción de" : "Reinscribir a"} ${row.student_name}`} onClick={() => onEdit(row)}>{row.status === "registered" ? <Pencil size={14} /> : <RotateCcw size={14} />}{row.status === "registered" ? "Editar" : "Reinscribir"}</button>{row.status === "registered" && <button className="tournament-icon-button danger" aria-label={`Dar de baja del torneo a ${row.student_name}`} title="Dar de baja del torneo" onClick={() => onWithdraw(row)}><UserMinus size={16} /></button>}</div></td>}</tr>)}</tbody></table></div>
    {!filtered.length && <div className="tournament-empty"><h4>No hay alumnos con estos filtros</h4><p>{registrations.length ? "Cambia el equipo, el estado o la búsqueda para ver otras inscripciones." : "Inscríbelos a este torneo y asígnalos a los equipos que ya creaste."}</p></div>}<footer className="tournament-pagination"><span>{filtered.length} resultados</span>{pages > 1 && <div><button disabled={!page} onClick={() => setPage(value => value - 1)} className="tournament-button secondary compact">Anterior</button><span>{page + 1} / {pages}</span><button disabled={page >= pages - 1} onClick={() => setPage(value => value + 1)} className="tournament-button secondary compact">Siguiente</button></div>}</footer>
  </section>;
}
