import { useState } from "react";
import { Plus } from "lucide-react";
import type { Match } from "../../types";
import { SelectInput, TextInput } from "../../components/views/shared";
import { Scoreboard } from "../../components/views/sportsCompetition";

export function TournamentMatches({ matches, canEdit, canSchedule, onSchedule, onUpdate, onCreateTeams }: { matches: Match[]; canEdit: boolean; canSchedule: boolean; onSchedule: () => void; onCreateTeams: () => void; onUpdate: (id: number, payload: unknown) => Promise<void> }) {
  const [status, setStatus] = useState("");
  const [query, setQuery] = useState("");
  const [limit, setLimit] = useState(8);
  const statusOrder = { live: 0, scheduled: 1, finished: 2, canceled: 3 };
  const filtered = matches.filter(row => (!status || row.status === status) && `${row.home_team_name} ${row.away_team_name} ${row.played_on}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a, b) => statusOrder[a.status] - statusOrder[b.status] || (a.status === "finished" ? b.played_on.localeCompare(a.played_on) : a.played_on.localeCompare(b.played_on)) || (a.starts_at || "").localeCompare(b.starts_at || ""));
  return <section className="tournament-surface" data-testid="tournament-matches"><header className="tournament-section-heading"><div><h3>Todos los partidos</h3><p>{matches.length} partidos · {matches.filter(row => row.status === "live").length} en vivo · {matches.filter(row => row.status === "scheduled").length} programados</p></div>{canEdit && <button className="tournament-button primary" disabled={!canSchedule} onClick={onSchedule}><Plus size={16} />Agendar partido</button>}</header>{canEdit && !canSchedule && <div className="tournament-feedback warning">Necesitas al menos dos equipos activos para agendar un partido. <button className="tournament-text-button" onClick={onCreateTeams}>Crear equipos</button></div>}<div className="tournament-match-filters"><TextInput label="Buscar partido" placeholder="Equipo o fecha (AAAA-MM-DD)" value={query} onChange={event => { setQuery(event.target.value); setLimit(8); }} /><SelectInput label="Estado del partido" value={status} onChange={event => { setStatus(event.target.value); setLimit(8); }}><option value="">Todos, incluidos cancelados</option><option value="live">En vivo</option><option value="scheduled">Programados</option><option value="finished">Finalizados</option><option value="canceled">Cancelados</option></SelectInput></div><div className="sports-matches">{filtered.slice(0, limit).map(match => <Scoreboard key={match.id} match={match} canEdit={canEdit} onUpdateMatch={onUpdate} />)}</div>{!filtered.length && <div className="tournament-empty"><h4>{matches.length ? "Sin partidos con estos filtros" : "Aún no hay partidos"}</h4><p>{matches.length ? "Prueba con otro equipo o estado." : "Agenda el primero para comenzar el calendario del torneo."}</p></div>}{filtered.length > limit && <div className="tournament-actions centered"><button className="tournament-button secondary" onClick={() => setLimit(value => value + 8)}>Ver más partidos ({filtered.length - limit} restantes)</button></div>}</section>;
}
